# Generated by Django 5.0.6 on 2025-01-19 12:19

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to=users.models.Profile.allowed_groups, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
