# Generated by Django 5.0.6 on 2025-02-02 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('is_portfolio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portfolio_desc', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_cash_balance', models.FloatField(default=0)),
                ('units', models.FloatField(default=1)),
            ],
            options={
                'ordering': ['portfolio_desc'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_price', models.FloatField(blank=True, default=0, null=True)),
                ('no_of_shares', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_trades', models.IntegerField(blank=True, default=0, null=True)),
                ('holding_value', models.FloatField(blank=True, default=0, null=True)),
                ('stop_loss', models.FloatField(blank=True, default=0, null=True)),
                ('cash_out', models.FloatField(blank=True, default=0, null=True)),
                ('comment', models.TextField(null=True)),
                ('svg_content', models.TextField(null=True)),
            ],
            options={
                'ordering': ['portfolio'],
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField()),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='portfolios.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_object_id', models.UUIDField(blank=True, null=True)),
                ('balance', models.FloatField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('units', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['profile', 'portfolio']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
