# Generated by Django 5.0.6 on 2025-01-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_cash_balance',
            field=models.FloatField(default=0),
        ),
    ]
