# Generated by Django 5.0.6 on 2025-01-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_cash_updated_at_portfolio_total_cash_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
    ]
