# Generated by Django 5.0.6 on 2025-01-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_asset_is_portfolio_asset_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='units',
            field=models.FloatField(default=0),
        ),
    ]
