# Generated by Django 5.0.6 on 2025-01-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolios', '0008_cash_units_alter_portfolio_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='user',
        ),
        migrations.AddField(
            model_name='cash',
            name='owner_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['profile', 'portfolio']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cash',
            name='owner_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
