# Generated by Django 5.0.6 on 2025-01-25 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_remove_cash_user_cash_owner_content_type_and_more'),
        ('users', '0005_profile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='owner_content_type',
        ),
        migrations.RemoveField(
            model_name='cash',
            name='owner_object_id',
        ),
        migrations.AddField(
            model_name='cash',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cash_balances', to='users.profile'),
            preserve_default=False,
        ),
    ]
