# Generated by Django 5.0.6 on 2025-01-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_remove_cash_user_cash_owner_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='owner_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
